server:
  port: 8895
spring:
  application:
    name: ribbon-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8890/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'