server:
  port: 8030
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ityouknow/spring-cloud-examples  #https://github.com/yangry0917/springcloud-config.git #https://github.com/ityouknow/spring-cloud-examples    # 配置git仓库的地址
          search-paths: config-repo                         # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/