# http://localhost:8050/auth/server/oauth/authorize?response_type=code&client_id=client_1&redirect_uri=http://localhost:8060/user/resource/oauth/callback
spring:
  application:
    name: user-resource-server
  #链路服务的地址
  zipkin:
    base-url: http://localhost:9411
  #被追踪的可能性，默认是0.1 表示百分之10
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
server:
  port: 8060
  servlet:
    context-path: /user/resource

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis:
#  mapper-locations: classpath:mappers/*.xml
  #打印sql到控制台
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  oauth2:
    authorization:
      check-token-access: http://localhost:8050/auth/server/oauth/check_token
    client:
      access-token-uri: http://localhost:8050/auth/server/oauth/token
      authorized-grant-types: authorization_code
      client-id: client_1 #user-service
      client-secret: secret_1
      registered-redirect-uri: http://localhost:8060/user/resource/oauth/callback
      user-authorization-uri: http://localhost:8050/auth/server/oauth/authorize
    resource:
      token-info-uri: http://localhost:8050/auth/server/oauth/check_token

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/
