server:
  port: 8050
#  servlet:
#    context-path: /auth/server

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/,http://peer3:8002/eureka/

spring:
  application:
    name: oauth2-authserver
  #链路服务的地址
  zipkin:
    base-url: http://localhost:9411
  #被追踪的可能性，默认是0.1 表示百分之10
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  thymeleaf:
    cache: false #关闭页面缓存
    encoding: UTF-8 #模板编码
    prefix: classpath:/templates/ #页面映射路径
    suffix: .html #视图的后缀
    mode: HTML5 #模板模式
  redis:
    database: 1
    host: 192.168.4.17
    port: 6379
    password: 123456
    timeout: 1800

feign:
  hystrix:
    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 30000